/**
 * Marketing-site sample documents.
 *
 * The PDF assets are generated by
 * ``backend/scripts/generate_marketing_sample_pdfs.py`` and committed under
 * ``frontend/public/samples/`` so the marketing site can serve them as
 * static files. Keep this list in sync with the SAMPLES tuple in that
 * generator script.
 */
export type SampleDocument = {
  id: "executive-brief" | "insurance-form" | "legal-defense-packet";
  title: string;
  shortTitle: string;
  audience: string;
  whenProduced: string;
  description: string;
  /** Path under /public, served as a static asset by Next.js. */
  pdfHref: string;
  /** Short filename used as a download attribute. */
  downloadFileName: string;
};

export const SAMPLE_DOCUMENTS: readonly SampleDocument[] = [
  {
    id: "executive-brief",
    title: "Initial Executive Brief",
    shortTitle: "Executive Brief",
    audience: "Safety leadership, claims, dispatch",
    whenProduced: "Sent within minutes of an incident being opened",
    description:
      "An at-a-glance brief auto-generated when a collision is detected: driver, tractor/trailer, dispatch, dock, weigh station, ELD, and dashcam links — everything stakeholders need before they pick up the phone.",
    pdfHref: "/samples/adc-sample-executive-brief.pdf",
    downloadFileName: "adc-sample-executive-brief.pdf",
  },
  {
    id: "insurance-form",
    title: "Insurance Company Fillable Form",
    shortTitle: "Insurance Form",
    audience: "Claims teams, insurance carriers",
    whenProduced: "Pre-filled from incident data the moment it's available",
    description:
      "A carrier-specific FNOL form pre-filled from the canonical incident record. Each field shows its source path; required fields still pending exchange (e.g. claim number from carrier) are flagged so claims teams know exactly what's left to gather.",
    pdfHref: "/samples/adc-sample-insurance-form.pdf",
    downloadFileName: "adc-sample-insurance-form.pdf",
  },
  {
    id: "legal-defense-packet",
    title: "Legal Defense Packet",
    shortTitle: "Legal Defense Packet",
    audience: "Defense counsel, in-house legal",
    whenProduced: "Generated on demand for litigation",
    description:
      "A litigation-grade packet matching the court_defense_v1 profile: cover, incident summary, evidence inventory, chain-of-custody, timeline, driver statement, telemetry highlights, media inventory, and a SHA-256 integrity attestation.",
    pdfHref: "/samples/adc-sample-legal-defense-packet.pdf",
    downloadFileName: "adc-sample-legal-defense-packet.pdf",
  },
] as const;
