"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import MainLayout from "@/components/MainLayout";
import IncidentFilterBar, { type IncidentFilters } from "@/components/case-ops/IncidentFilterBar";
import IncidentQueueTable, { type QueueTabKey } from "@/components/case-ops/IncidentQueueTable";
import { Alert, Badge, Button, Card, CardContent, CardHeader, EmptyState, MetricCard, PageHeader, Skeleton } from "@/components/ui";
import { getIntegrationValidationResults, getIncidentAlerts, getIncidentQueue, getIncidentSummaryMetrics, getOrgOnboardingQrStats, getOrgOnboardingStatus, getMyOpenTasks, getOverdueTasks, patchIncidentOwner, patchIncidentStatus, toUserErrorMessage, type CaseOpsAlerts, type CaseOpsQueueItem, type CaseOpsSummaryMetrics, type CaseStatus, type CaseTaskWidgetItem, type IntegrationValidationResult, type OrgLaunchReadiness, type VehicleQrStats } from "@/lib/api";
import { buildAttentionItems, buildOperationalMetrics, caseLabel, sortPriorityCases } from "@/lib/commandCenter";
import { ONBOARDING_WIZARD_STORAGE_KEY } from "@/lib/onboarding";
import { useAuth } from "@/lib/useAuth";

const DEFAULT_FILTERS: IncidentFilters = { status: "", readiness_state: "", blockers: "", search: "", sort: "urgency" };
const QUEUE_PAGE_SIZE = 50;
const QUEUE_ALL_PAGE_SIZE = 500;

function buildQueueParams(filters: IncidentFilters, includeStatus = true) { return { ...(includeStatus && filters.status ? { status: filters.status } : {}), readiness_state: filters.readiness_state || undefined, blockers: filters.blockers || undefined, search: filters.search || undefined, sort: filters.sort, page: 1 }; }
const TAB_TO_STATUS: Record<QueueTabKey, string> = { all: "", new: "new", in_review: "in_review", awaiting_evidence: "awaiting_evidence", ready_for_export: "ready_for_export", escalated: "escalated", awaiting_follow_up: "awaiting_follow_up", exported: "exported", closed: "closed" };
function mergeFilters(filters: IncidentFilters, patch: Partial<IncidentFilters>): IncidentFilters { return { ...filters, ...patch }; }

function getInitialFilters(): IncidentFilters { if (typeof window === "undefined") return DEFAULT_FILTERS; const params = new URLSearchParams(window.location.search); return { status: params.get("status") ?? "", readiness_state: params.get("readiness_state") ?? "", blockers: params.get("blockers") ?? "", search: params.get("search") ?? "", sort: (params.get("sort") as IncidentFilters["sort"]) ?? "urgency" }; }

function MetricsGrid({ metrics, queueAll, overdueTasks, loading, error }: { metrics: CaseOpsSummaryMetrics | null; queueAll: CaseOpsQueueItem[]; overdueTasks: CaseTaskWidgetItem[]; loading: boolean; error: string }) {
  const values = buildOperationalMetrics({ queue: queueAll, metrics, overdueTasks });
  if (error && !metrics) return <Alert tone="critical" title="Metrics unavailable" description={error} />;
  return <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Primary operational metrics"><MetricCard label="Active Cases" value={values.activeCases} message="Cases not closed in the command queue" loading={loading}/><MetricCard label="Need Action" value={values.needAction} message="Blocked, escalated, or missing required evidence" status="warning" loading={loading}/><MetricCard label="Ready for Export" value={values.exportReady} message="Defense packets can be generated" status="success" loading={loading}/><MetricCard label="Overdue" value={values.overdue} message="Follow-up required now" status="critical" loading={loading}/></section>;
}

function NeedsAttention({ alerts, queue, overdueTasks, loading, error, onFilter }: { alerts: CaseOpsAlerts | null; queue: CaseOpsQueueItem[]; overdueTasks: CaseTaskWidgetItem[]; loading: boolean; error: string; onFilter: (patch: Partial<IncidentFilters>) => void }) {
  const items = buildAttentionItems({ alerts, queue, overdueTasks });
  return <Card><CardHeader title="Needs Attention" description="Actionable categories supported by current dashboard data."/><CardContent>{loading ? <div className="space-y-3"><Skeleton className="h-12"/><Skeleton className="h-12"/><Skeleton className="h-12"/></div> : null}{!loading && error ? <Alert tone="critical" title="Attention panel unavailable" description={error}/> : null}{!loading && !error && items.length === 0 ? <EmptyState title="No attention items" message="There are no critical blockers, overdue follow-ups, or export-ready items in the loaded queue."/> : null}{!loading && !error && items.length > 0 ? <ul className="space-y-3">{items.map((item) => <li key={item.key} className="rounded-lg border border-border-subtle bg-surface-subtle p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-text-primary">{item.label}</p><p className="mt-1 text-sm text-text-secondary">{item.explanation}</p></div><Badge>{item.count}</Badge></div><Button variant="quiet" size="sm" className="mt-2" onClick={() => onFilter(item.filter)}>Show cases</Button></li>)}</ul> : null}</CardContent></Card>;
}

export default function DashboardClient() {
  const { user } = useAuth(); const router = useRouter(); const searchParams = useSearchParams(); const isDemoMode = searchParams?.get("demo") === "1";
  const [filters, setFilters] = useState<IncidentFilters>(getInitialFilters); const [queue, setQueue] = useState<CaseOpsQueueItem[]>([]); const [queueAll, setQueueAll] = useState<CaseOpsQueueItem[]>([]); const [metrics, setMetrics] = useState<CaseOpsSummaryMetrics | null>(null); const [alerts, setAlerts] = useState<CaseOpsAlerts | null>(null); const [overdueTasks, setOverdueTasks] = useState<CaseTaskWidgetItem[]>([]); const [myOpenTasks, setMyOpenTasks] = useState<CaseTaskWidgetItem[]>([]); const [queueLoading, setQueueLoading] = useState(true); const [overviewLoading, setOverviewLoading] = useState(true); const [queueError, setQueueError] = useState(""); const [overviewError, setOverviewError] = useState(""); const [actionError, setActionError] = useState(""); const [, setOnboarding] = useState<OrgLaunchReadiness | null>(null); const [, setQrStats] = useState<VehicleQrStats | null>(null); const [, setIntegrationValidationResults] = useState<IntegrationValidationResult[]>([]); const [demoTourDismissed, setDemoTourDismissed] = useState(false);
  const activeTab = (Object.keys(TAB_TO_STATUS).find((key) => TAB_TO_STATUS[key as QueueTabKey] === filters.status) as QueueTabKey | undefined) ?? "all";
  const resumeOnboardingHref = useMemo(() => { if (typeof window === "undefined") return "/onboarding"; const persistedStep = window.localStorage.getItem(ONBOARDING_WIZARD_STORAGE_KEY); return persistedStep ? `/onboarding?step=${encodeURIComponent(persistedStep)}` : "/onboarding"; }, []);
  const firstPriority = useMemo(() => sortPriorityCases(queue)[0], [queue]); const firstDemoIncidentId = firstPriority?.incident_id ?? queueAll[0]?.incident_id ?? null;

  useEffect(() => { if (!user) return; Promise.all([getIncidentQueue({ ...buildQueueParams(filters), page_size: QUEUE_PAGE_SIZE }), getIncidentQueue({ ...buildQueueParams(filters, false), page_size: QUEUE_ALL_PAGE_SIZE })]).then(([filtered, unfiltered]) => { setQueue(filtered.items); setQueueAll(unfiltered.items); setQueueError(""); }).catch((err) => setQueueError(toUserErrorMessage(err, "Failed to load queue"))).finally(() => setQueueLoading(false)); }, [filters, user]);
  useEffect(() => { if (!user) return; Promise.all([getIncidentSummaryMetrics(), getIncidentAlerts(), getOverdueTasks({ limit: 20 }), getMyOpenTasks({ limit: 20 })]).then(async ([summary, alertPayload, overdue, mine]) => { const onboardingResults = await Promise.allSettled([getOrgOnboardingStatus(), getOrgOnboardingQrStats(), getIntegrationValidationResults()]); setMetrics(summary); setAlerts(alertPayload); setOverdueTasks(overdue.items); setMyOpenTasks(mine.items); setOnboarding(onboardingResults[0].status === "fulfilled" ? onboardingResults[0].value : null); setQrStats(onboardingResults[1].status === "fulfilled" ? onboardingResults[1].value : null); setIntegrationValidationResults(onboardingResults[2].status === "fulfilled" ? onboardingResults[2].value : []); setOverviewError(""); }).catch((err) => setOverviewError(toUserErrorMessage(err, "Failed to load command center"))).finally(() => setOverviewLoading(false)); }, [user]);

  const tabCounts = useMemo(() => { const counts: Record<QueueTabKey, number> = { all: queueAll.length, new: 0, in_review: 0, awaiting_evidence: 0, ready_for_export: 0, escalated: 0, awaiting_follow_up: 0, exported: 0, closed: 0 }; for (const item of queueAll) if (item.case_status in counts) counts[item.case_status as QueueTabKey] += 1; return Object.entries({ all: "All", new: "New", in_review: "In Review", awaiting_evidence: "Awaiting Evidence", ready_for_export: "Ready for Export", escalated: "Escalated", awaiting_follow_up: "Awaiting Follow-Up", exported: "Exported", closed: "Closed" }).map(([key, label]) => ({ key: key as QueueTabKey, label, count: counts[key as QueueTabKey] })); }, [queueAll]);
  const updateFilters = (next: IncidentFilters) => { setFilters(next); setQueueLoading(true); const query = new URLSearchParams(); if (next.status) query.set("status", next.status); if (next.readiness_state) query.set("readiness_state", next.readiness_state); if (next.blockers) query.set("blockers", next.blockers); if (next.search) query.set("search", next.search); if (next.sort) query.set("sort", next.sort); if (isDemoMode) query.set("demo", "1"); router.replace(query.toString() ? `/dashboard?${query.toString()}` : "/dashboard"); };
  const refreshQueue = () => { setQueueLoading(true); Promise.all([getIncidentQueue({ ...buildQueueParams(filters), page_size: QUEUE_PAGE_SIZE }), getIncidentQueue({ ...buildQueueParams(filters, false), page_size: QUEUE_ALL_PAGE_SIZE })]).then(([filtered, unfiltered]) => { setQueue(filtered.items); setQueueAll(unfiltered.items); setQueueError(""); }).catch((err) => setQueueError(toUserErrorMessage(err, "Failed to reload queue"))).finally(() => setQueueLoading(false)); };
  const onAssignMe = async (incidentId: string) => { if (!user) return; try { setActionError(""); await patchIncidentOwner(incidentId, { operation: "assign", owner_user_id: user.user_id }); refreshQueue(); } catch (err) { setActionError(toUserErrorMessage(err, "Failed to assign owner")); } };
  const onCaseStatusChange = async (incidentId: string, caseStatus: CaseStatus) => { try { setActionError(""); await patchIncidentStatus(incidentId, { case_status: caseStatus, reason: "Updated from command center" }); refreshQueue(); } catch (err) { setActionError(toUserErrorMessage(err, "Failed to change status")); } };
  const onCopyCaseId = (incidentId: string) => { void navigator.clipboard?.writeText(incidentId); };
  const attentionTasks = overdueTasks.length > 0 ? overdueTasks : myOpenTasks.filter((task) => task.status !== "completed");

  return <MainLayout title="Command Center"><div className="space-y-5"><PageHeader title="Incident Command Center" description="Monitor active cases, resolve blockers, and prepare defense-ready records." metadata={firstPriority ? <>Next best action: open <strong>{caseLabel(firstPriority)}</strong> and resolve {firstPriority.blockers.critical} critical blockers.</> : "No active incidents in the current queue."} primaryAction={<Button onClick={() => router.push("/incidents?quick=create")}>Create Incident</Button>} secondaryActions={<Button variant="secondary" onClick={() => router.push(resumeOnboardingHref)}>Resume onboarding</Button>}/>
  {isDemoMode && !demoTourDismissed ? <Alert tone="informational" title={<span><Badge>Demo Tour · Step 1 of 4</Badge> Review the priority incident</span>} description="Review the priority incident and identify its missing evidence." action={<div className="flex gap-2"><Button size="sm" onClick={() => firstDemoIncidentId && router.push(`/incidents/${firstDemoIncidentId}`)} disabled={!firstDemoIncidentId}>Open priority incident</Button><Button variant="secondary" size="sm" onClick={() => router.push("/exports")}>View exports</Button><Button variant="quiet" size="sm" onClick={() => router.push("/demo")}>Demo workspace</Button></div>} aria-label="Dismiss demo tour" onDismiss={() => setDemoTourDismissed(true)} data-testid="demo-tour-banner" /> : null}
  {overviewError ? <Alert tone="critical" title="Command center partially unavailable" description={overviewError}/> : null}{actionError ? <Alert tone="critical" title="Action failed" description={actionError}/> : null}
  <MetricsGrid metrics={metrics} queueAll={queueAll} overdueTasks={overdueTasks} loading={overviewLoading} error={overviewError}/>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,2.4fr)_minmax(300px,0.9fr)]"><div className="space-y-4"><IncidentFilterBar filters={filters} onChange={updateFilters} onReset={() => updateFilters(DEFAULT_FILTERS)} loading={queueLoading}/><IncidentQueueTable items={queue} loading={queueLoading} error={queueError} tabs={tabCounts} activeTab={activeTab} onTabChange={(tab) => updateFilters({ ...filters, status: TAB_TO_STATUS[tab] })} onOpen={(incidentId) => router.push(`/incidents/${incidentId}`)} onAssignMe={onAssignMe} onCaseStatusChange={onCaseStatusChange} onCopyCaseId={onCopyCaseId}/></div><aside><NeedsAttention alerts={alerts} queue={queueAll} overdueTasks={attentionTasks} loading={overviewLoading || queueLoading} error={overviewError} onFilter={(patch) => updateFilters(mergeFilters(filters, patch))}/></aside></div></div></MainLayout>;
}
